FROM eclipse-temurin:17
LABEL authors="ramakrishna"

WORKDIR /app

COPY target/springboot-restful-webservices-0.0.1-SNAPSHOT.jar /app/springboot-restful-webservices.jar

ENTRYPOINT ["java", "-jar", "/app/springboot-restful-webservices.jar"]