package com.example.spring.demo.springdemo;

import com.example.spring.demo.componentScan.ComponentDAO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan("com.example.spring.demo.componentScan")
public class SpringComponentScanDemoApplication {

    private static final Logger LOGGER = LoggerFactory.getLogger(SpringComponentScanDemoApplication.class);

    public static void main(String[] args) {
//		SpringApplication.run(SpringDemoApplication.class, args);   // Autogenerated by spring starter io
//        ApplicationContext applicationContext = SpringApplication.run(SpringComponentScanDemoApplication.class, args);
        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(SpringComponentScanDemoApplication.class);

        ComponentDAO componentDAO = applicationContext.getBean(ComponentDAO.class);

        LOGGER.info("{}", componentDAO);

    }

}
