package com.example.spring.demo.springdemo;

import com.example.spring.demo.springdemo.basic.BinarySearchImpl;
import com.example.spring.demo.springdemo.basic.QuickSortAlgorithm;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan
public class SpringBasicDemoApplication {

    private static Logger LOGGER = LoggerFactory.getLogger(SpringBasicDemoApplication.class);

    public static void main(String[] args) {
//		SpringApplication.run(SpringDemoApplication.class, args);   //Autogenerated by spring starter io
//        ApplicationContext applicationContext = SpringApplication.run(SpringBasicDemoApplication.class, args);
        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(SpringBasicDemoApplication.class);

        BinarySearchImpl binarySearch = applicationContext.getBean(BinarySearchImpl.class);
        BinarySearchImpl binarySearch1 = applicationContext.getBean(BinarySearchImpl.class);
        int[] numbers = new int[] {12, 3, 5};
        System.out.println(binarySearch.binarySearch(numbers, 5));

        binarySearch.setSortAlgorithm(new QuickSortAlgorithm());
        System.out.println(binarySearch.binarySearch(numbers, 5));

        LOGGER.info("{}", binarySearch);
        LOGGER.info("{}", binarySearch1);

//        System.exit(0);
    }

}
